server:
  port: 8172

spring:
  application:
    name: api-gateway
  config:
    import: configserver:http://localhost:8085
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service
          predicates:
            - Path=/product-service/**
          filters:
            - StripPrefix=1
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user-service/**
          filters:
            - StripPrefix=1
        - id: bag-service
          uri: lb://bag-service
          predicates:
            - Path=/bag-service/**
          filters:
            - StripPrefix=1
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order-service/**
          filters:
            - StripPrefix=1
        - id: registry
          uri: lb://registry
          predicates:
            - Path=/registry/**
          filters:
            - StripPrefix=1
        - id: eureka
          uri: lb://registry
          predicates:
            - Path=/eureka/**

info:
  app:
    name: ${spring.application.name}

#eureka:
#  client:
#    registerWithEureka: true
#    serviceUrl:
#      defaultZone: ${EUREKA_SERVER:http://localhost:8171/eureka}
#    healthcheck:
#      enabled: true

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka

#management:
#  endpoints:
#    web:
#      exposure:
#        include:
#          - mappings
#          - env
#          - health
#          - info