server:
  port: 8082

spring:
  application:
    name: user-service
  config:
    activate:
      on-profile: local
    import: "optional:configserver:"
#    config:
#      enabled: true
  cloud:
    bus:
      enabled: true # Enable Cloud Bus
    stream:
      kafka:
        binder:
          brokers: localhost:9092 # Kafka broker address
          default-binder: true
        bindings:
          output:
            destination: config-bus-topic # Kafka topic used for bus events




    # Configure the message broker connection (RabbitMQ or Kafka)


#  cloud:
#    config:
#      uri: http://${CONFIG_SERVER_SERVICE_SERVICE_HOST:localhost}:8085
#    bus:
#      enabled: true
#      refresh:
#        enabled: true
#      trace:
#        enabled: true
#  rabbitmq:
#    addresses: ${RABBITMQ_SERVICE_SERVICE_HOST:localhost}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}  #eureka endpoint
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    hostname: localhost