server:
  port: 8081
#server:
#  port: 0 # to run multiple instances on random ports
spring:
  application:
    name: product-service

  config:
    import: configserver:http://localhost:8085
#  profiles:
#    active: prod


#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka  #eureka endpoint
#
#    healthcheck:
#      enabled: true

#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#    hostname: localhost