server:
  port: 8081
#server:
#  port: 0 # to run multiple instances on random ports
spring:
  config:
    import: configserver:http://localhost:8085
#
#    # Configure the message broker connection (RabbitMQ or Kafka)
#  cloud:
#    config:
#      uri: http://${CONFIG_SERVER_SERVICE_SERVICE_HOST:localhost}:8085
#    bus:
#      enabled: true
#      refresh:
#        enabled: true
#      trace:
#        enabled: true
#  rabbitmq:
#    addresses: ${RABBITMQ_SERVICE_SERVICE_HOST:localhost}
#  profiles:
#    active: prod

# Enable the Actuator endpoints
#management:
#  endpoints:
#    web:
#      exposure:
#        include: "*"

#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka  #eureka endpoint
#
#    healthcheck:
#      enabled: true

#  instance:
#    leaseRenewalIntervalInSeconds: 1
#    leaseExpirationDurationInSeconds: 2
#    hostname: localhost