server:
  port: 8085

spring:
  application:
    name: config-service
  config:
    activate:
      on-profile: local
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Lokesh598/order-management-spring-cloud-config
          default-label: main
          clone-on-start: true
    monitor:
      enabled: true
    bus:
      enabled: false
    stream:
      kafka:
        binder:
          brokers: localhost:9092
        bindings:
          output:
            destination: config-server

  management:
    endpoints:
      web:
        exposure:
          include: "*"

    # Configure the message broker connection (RabbitMQ or Kafka)
#  cloud:
#    config:
#      uri: http://${CONFIG_SERVER_SERVICE_SERVICE_HOST:localhost}:8085
#    bus:
#      enabled: true
#      refresh:
#        enabled: true
#      trace:
#        enabled: true
#  rabbitmq:
#    addresses: ${RABBITMQ_SERVICE_SERVICE_HOST:localhost}
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}  #eureka endpoint
    healthcheck:
      enabled: true
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
    hostname: localhost