name: Java CI with Maven (User Service)

on:
  push:
    branches: [ "action_build" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@v4

      # Step 2: Set up JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Debug - List directory contents
      - name: List directory contents
        run: ls -R

      # Step 4: Build the Maven project in the user-service directory
      - name: Build user-service with Maven
        run: mvn -B package --file user-service/pom.xml

      # Optional: Update dependency graph for Dependabot
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
